### PR TITLE
Use branch automerge strategy

### PR DESCRIPTION
**Pull request by pat-s**
Strategy description:

- Renovate first creates a branch and no PR
- If **tests pass**, Renovate pushes a commit directly to the base branch without PR
- If tests fail, Renovate raises a PR for you to review

Major updates are never automerged.

Source: https://docs.renovatebot.com/noise-reduction/#branch-automerging

### CODE REVIEW

**Comment by pat-s** [comment]
Major deps are should never get automerged as we have `"automergeMajor": false,` set.

Can you show a PR where this happened? I only found the "non-major golang deps" ones which look good to me (e.g. https://github.com/woodpecker-ci/woodpecker/pull/2566).

**Comment by pat-s** [comment]
This is a major update and wouldn't have been automerged. 

Not all updates work OOB and this is more often to happen for major ones anyhow. Not sure if the manual work done by you is a one time fix or would be required next time again (for this I am not enough of an expert on go). I also can't see if the CI of the first commit succeeded (it's yellow and I'm on the phone). 

But WRT to your initial comment about potential automerges which don't work: I think for golang, as long as the tests work it should be fine? I.e. due to the coverage, CI should always fail if there really is an issue - shouldn't it?

**Comment by pat-s** [comment]
If this is a specific issue with major upgrades, I guess something can/should be done on the renovate side then. 
Maybe somebody already reported it? 

The only thing I am concerned about is if something would be merged which causes an issue/does not work. Imperfect updates of certain deps are not great but something we/you can easily workaround. 

But thanks for asking and for the approval! Let's see how it goes, I have great hopes that it will help in a good way.

**Comment by pat-s** [comment]
@anbraten could you activate the renovate-approve bot for all repos in the org?

**Comment by anbraten** [comment]
> @anbraten could you activate the renovate-approve bot for all repos in the org?

How do I have to do this again 😅

**Comment by anbraten** [comment]
Should be adjusted now

**Pull request merged**
